import './polyfills';
import 'core-js/client/shim';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import '@angular/platform-browser-dynamic';
import '@angular/core/testing';
import '@angular/platform-browser-dynamic/testing';
import '@angular/router';
import '@angular/forms';
import '@angular/material';
import '@ngrx/store';
import '@ngrx/router-store';
